//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::E0, // Inyector1 (E0)
	Gpio::E1, // Inyector2 (E1)
	Gpio::E2, // Inyector3 (E2)
	Gpio::E3, // Inyector4 (E3)
	Gpio::E4, // Bobina1 (E4)
	Gpio::E5, // Bobina2 (E5)
	Gpio::E6, // Bobina3 (E6)
	Gpio::E7, // Bobina4 (E7)
	Gpio::B5, // Output (B5)
	Gpio::B6, // Output (B6)
	Gpio::B7, // Output (B7)
	Gpio::B8, // Output (B8)
	Gpio::B9, // Output (B9)
	Gpio::B10, // MainRelay (B10)
	Gpio::B11, // FuelPump (B11)
	Gpio::B13, // TachOut (B13)
	Gpio::B14, // FanRelay1 (B14)
	Gpio::B15, // FanRelay2 (B15)
// "Inyector1 (E0)",
// "Inyector2 (E1)",
// "Inyector3 (E2)",
// "Inyector4 (E3)",
// "Bobina1 (E4)",
// "Bobina2 (E5)",
// "Bobina3 (E6)",
// "Bobina4 (E7)",
// "Output (B5)",
// "Output (B6)",
// "Output (B7)",
// "Output (B8)",
// "Output (B9)",
// "MainRelay (B10)",
// "FuelPump (B11)",
// "TachOut (B13)",
// "FanRelay1 (B14)",
// "FanRelay2 (B15)",
}
