//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#pragma once

Gpio GENERATED_OUTPUTS = {
	Gpio::B14, // B14 Output
	Gpio::E0, // Inyector 1
	Gpio::E1, // Inyector 2
	Gpio::E2, // Inyector 3
	Gpio::E3, // Inyector 4
	Gpio::E4, // Bobina 1
	Gpio::E5, // Bobina 2
	Gpio::E6, // Bobina 3
	Gpio::E7, // Bobina 4
// "B14 Output",
// "Inyector 1",
// "Inyector 2",
// "Inyector 3",
// "Inyector 4",
// "Bobina 1",
// "Bobina 2",
// "Bobina 3",
// "Bobina 4",
}
