//DO NOT EDIT MANUALLY, let automation work hard.

// auto-generated by PinoutLogic.java based on ../../../connectors/custom_firmware.yaml
#include "pch.h"

// see comments at declaration in pin_repository.h
const char * getBoardSpecificPinName(brain_pin_e brainPin) {
	switch(brainPin) {
		case Gpio::B5: return "Output (B5)";
		case Gpio::B6: return "Output (B6)";
		case Gpio::B7: return "Output (B7)";
		case Gpio::B8: return "Output (B8)";
		case Gpio::B9: return "Output (B9)";
		case Gpio::C6: return "VR/Hall 1 (C6)";
		case Gpio::C7: return "VR/Hall 2 (C7)";
		case Gpio::E0: return "Inyector1 (E0)";
		case Gpio::E1: return "Inyector2 (E1)";
		case Gpio::E12: return "Bobina4 (E12)";
		case Gpio::E2: return "Inyector3 (E2)";
		case Gpio::E3: return "Inyector4 (E3)";
		case Gpio::E4: return "Bobina1 (E4)";
		case Gpio::E5: return "Bobina2 (E5)";
		case Gpio::E6: return "Bobina3 (E6)";
		case Gpio::E7: return "Bobina4 (E7)";
		default: return nullptr;
	}
	return nullptr;
}
